name: wizards
description: "A flutter-based web application to demonstrate the use of Keycloak."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # For state management.
  flutter_bloc: ^9.1.0

  # For internationalization of the application.
  intl: ^0.20.2

  # For dynamic routing.
  go_router: ^15.1.1

  # For rendering lottie animations.
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
flutter_intl:
  enabled: true
