name: wizards
description: "A flutter-based web application to demonstrate the use of Keycloak."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # For localization.
  flutter_localizations:
    sdk: flutter

  # For state management.
  flutter_bloc: ^9.1.0

  # For internationalization of the application.
  intl: ^0.19.0

  # For dynamic routing.
  go_router: ^15.1.1

  # For rendering lottie animations.
  lottie: ^3.3.1

  # To establish connection between the OAuth 2.0 client and application.
  openid_client: ^0.4.9

  # To create signatures.
  crypto: ^3.0.6

  # For making HTTP requests.
  http: ^1.3.0

  # For storing data locally as key-value pairs.
  shared_preferences: ^2.5.3

  # For interacting with the web-browser.
  universal_html: ^2.2.4

dev_dependencies:
  # For writing tests.
  flutter_test:
    sdk: flutter

  # For linting.
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  # Custom fonts.
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Tangerine
      fonts:
        - asset: fonts/tangerine/Tangerine-Bold.ttf
        - asset: fonts/tangerine/Tangerine-Regular.ttf
  # The assets.
  assets:
    - assets/images/
    - assets/lottie/
